<a href="https://colab.research.google.com/github/Rahul-phyton-code/numpy-/blob/main/26_feb_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.) Array can store elements of only one data type but List can store the elements of different data types too. Hence, Array stores homogeneous data values, and the list can store heterogeneous data values.List is the in-build data structure of python language hence no module or package is to be imported before using it. But the array is not an in-build data structure for python language. Hence, we need to import the “array” module before creating and using arrays.

In [5]:
import numpy as np
list_ = ["1","2","3","4","5"]
array_list = np.array(object = list_)
print(type(list))
print(type(array_list))

<class 'type'>
<class 'numpy.ndarray'>


2.)

In [7]:
import numpy as np
list_ = ["1","2","3","4","5"]
array_list = np.array(object = list_)
for i in list_:
  print(type(i))
for x in array_list:
  print(type(x))  


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


3.) array_list = np.array(object = list_, dtype = int)

it represents the same meaning as in earlier example because it shows object is of variable name list_ which clearly given that list_ contain elements which are of integers class. The privilege is that is reduce the size of coding in contrast to previous one

In [9]:
import numpy as np
list_ = ["1","2","3","4","5"]
array_list = np.array(object = list_ , dtype = int)
for i in list_:
  print(type(i))
for x in array_list:
  print(type(x))  




<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


4.) 

In [12]:
import numpy as np
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(object=num_list)
num_array.shape
num_array.size

6

5.) 

In [18]:
import numpy as np
zero_matrix = np.ones((3,3))
zero_matrix1 = np.ones((3,3))
print(zero_matrix - zero_matrix1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


6.)

In [20]:
import numpy as np
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])